import { precacheAndRoute } from 'workbox-precaching';

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

self.addEventListener('push', function(event) {
  console.log('Push event received:', event);
  if (!event.data) {
    console.warn('Push event received but no data found');
    return;
  }
  
  try {
    const data = event.data.json();
    console.log('Push data parsed:', data);
    const title = data.title || 'ATR Store Alert';
    const options = {
      body: data.body || 'You have a new alert.',
      icon: 'https://picsum.photos/seed/inventory/192/192', // Use Picsum icon
      badge: 'https://picsum.photos/seed/inventory/72/72', // Use Picsum badge
      vibrate: [100, 50, 100],
      requireInteraction: true,
      data: {
        dateOfArrival: Date.now(),
        url: data.url || '/'
      },
      tag: 'inventory-alert',
      renotify: true
    };

    event.waitUntil(
      self.registration.showNotification(title, options)
    );
  } catch (err) {
    console.error('Error parsing push data:', err);
    // Fallback if not JSON
    const text = event.data.text();
    event.waitUntil(
      self.registration.showNotification('ATR Store Alert', {
        body: text,
        icon: 'https://picsum.photos/seed/inventory/192/192'
      })
    );
  }
});

self.addEventListener('notificationclick', function(event) {
  event.notification.close();
  const url = event.notification.data?.url || '/';
  
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then(function(clientList) {
      // For other links, try to focus an existing window
      for (let i = 0; i < clientList.length; i++) {
        const client = clientList[i];
        if (client.url === '/' && 'focus' in client) {
          return client.focus();
        }
      }
      if (clients.openWindow) {
        return clients.openWindow(url);
      }
    })
  );
});
